import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import TimerList from '@/components/timerList'
import WorldClock from '@/components/worldClock'

export default function Home() {
  return (
    <>
      <Head>
        <title>Countdown Tmer and World Clock App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
        <h1>Countdown Timer App</h1>
        <TimerList />
        </div>
        <div>
          <h1>World Clock</h1>
          <WorldClock/>
        </div>
      </main>    
    </>
  )
}
